version: '3.1'

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/test
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
